# Generated by Django 3.1.4 on 2020-12-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('added_in', models.DateTimeField(auto_now_add=True, verbose_name='adicionado em')),
            ],
            options={
                'verbose_name': 'artigo',
                'verbose_name_plural': 'artigos',
                'ordering': ('-added_in',),
            },
        ),
    ]
