# Generated by Django 3.1.4 on 2020-12-11 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='article',
            name='dnas',
            field=models.ManyToManyField(blank=True, to='core.DNA', verbose_name="DNA's"),
        ),
        migrations.AddField(
            model_name='article',
            name='photos',
            field=models.ManyToManyField(blank=True, to='core.Photo', verbose_name='fotos'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
