# Generated by Django 3.1.4 on 2020-12-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_reference_article'),
        ('articles', '0004_auto_20201213_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.photo', verbose_name='fotos'),
        ),
    ]
